[project]
name = "ahbackend"
version = "0.1.0"
description = "D3 Annotation Hub Backend"
authors = [{ name = "Emanuel Souza de Quadros" }]
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
dependencies = [
  "cryptography>=46.0.3",
  "d3textdb @ file:../d3textdb",
  "email-validator>=2.2.0",
  "fastapi[standard]>=0.115.12",
  "multimethod>=2.0",
  "passlib[bcrypt]>=1.7.4",
  "pydantic>=2.11.4",
  "pyjwt>=2.10.1",
  "python-multipart>=0.0.20",
  "sqlmodel>=0.0.24",
  "tokenizers>=0.21.1",
  "uvicorn>=0.34.2",
  "xmlparser @ git+ssh://git@github.com/manuquadros/xmlparser.git",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
  "autodoc-pydantic>=2.2.0",
  "beartype>=0.21.0",
  "black>=24",
  "debugpy>=1.8.14",
  "devtools>=0.12.2",
  "flake8-pyproject>=1.2.3",
  "flake8-type-checking>=3.0.0",
  "icecream>=2.1.4",
  "ipython-autotime>=0.3.2",
  "ipython>=9.4",
  "isort>=6.0.1",
  "mccabe>=0.7.0",
  "memray>=1.14.0",
  "pre-commit>=4.2.0",
  "prospector[with_everything]>=1.13.3",
  "pudb>=2024.1.3",
  "pydata-sphinx-theme>=0.16.0",
  "pyls-memestra>=0.0.16",
  "pylsp-mypy>=0.6.9",
  "pylsp-rope>=0.1.17",
  "pytest-asyncio>=1",
  "pytest-cov>=6.1.1",
  "pytest-memray>=1.7.0",
  "pytest-sugar>=1.0.0",
  "pytest-watcher>=0.4.3",
  "pytest>=8.3.4",
  "python-lsp-server>=1.12.2",
  "rich>=13.9.4",
  "rope>=1.13.0",
  "sphinx-book-theme>=1",
  "sphinx-pydantic>=0.1.1",
  "sphinx>=8.1.3",
  "stackprinter>=0.2.12",
  "types-tqdm>=4.67.0.20241221",
]

[tool.pdm.scripts]
dev = "python scripts/run.py"
lint = "flake8 ."
fmt = { composite = ["black .", "isort ."] }

[tool.flake8]
per-file-ignores = ["__init__.py:F401"]

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80

[tool.pylsp.plugins]
pylsp-mypy.enabled = true
