"""D3TextDB class and methods to interact with the database."""

import hashlib
import itertools
import json
import os
from datetime import datetime, timezone
from typing import Iterable
from uuid import UUID

import bcrypt
from pydantic import EmailStr
from sqlalchemy import create_engine
from sqlalchemy import delete as sa_delete
from sqlalchemy import event, func, literal_column, or_, select, text
from sqlalchemy.dialects.sqlite import insert
from sqlalchemy.orm import Session, aliased
from sqlalchemy.pool import StaticPool

from .owl import ParsedProperty, ParsedTriple
from .schema import (
    AnnotationSnapshot,
    AnnotationState,
    AnnotatorSnapshot,
    CuratedAnnotation,
    CuratedAnnotationPointer,
    CuratedAnnotationRelation,
    CurationDecision,
    Entity,
    EntityAnnotation,
    EntityName,
    Name,
    Ontology,
    OntologyProperty,
    ProposedProperty,
    Pointer,
    Project,
    ProjectMembership,
    ProjectOntology,
    ProjectReference,
    Reference,
    ReferenceAnnotation,
    Relation,
    SnapshotPointer,
    SnapshotRelation,
    SQLModel,
    StatePointer,
    StateRelation,
    Triple,
    User,
    UserAuth,
    UserLastProject,
    UserRelationReference,
    Verdict,
)


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode(
        "utf-8"
    )


def _content_hash(pointers: list[Pointer], relations: list[Relation]) -> str:
    """Compute a deterministic SHA-256 hash of the annotation content."""
    pointer_data = sorted((p.entity_id, p.field, p.offset, p.length) for p in pointers)
    relation_data = sorted(
        (r.predicate, r.subject, r.object) for r in relations
    )
    payload = json.dumps(
        {"pointers": pointer_data, "relations": relation_data}, sort_keys=True
    )
    return hashlib.sha256(payload.encode()).hexdigest()


class D3TextDB:
    def __init__(
        self,
        path: os.PathLike | None = None,
        echo: bool = False,  # noqa: FBT001, FBT002
    ) -> None:
        """Initialize the database layer.

        :param path: Location of the database file. If not provided, start an
            in-memory database.
        :param echo: Flag determining whether to output the SQL commands
            generated by SQLAlchemy.
        """
        if path:
            self.engine = create_engine(f"sqlite:///{path}", echo=echo)
        else:
            self.engine = create_engine(
                "sqlite://",
                echo=echo,
                connect_args={"check_same_thread": False},
                poolclass=StaticPool,
            )

        event.listen(
            self.engine,
            "connect",
            lambda dbapi_con, _: dbapi_con.execute("pragma foreign_keys=ON"),
        )
        SQLModel.metadata.create_all(self.engine)
        self._setup_fts()

    def __del__(self) -> None:
        self.engine.dispose()

    def _setup_fts(self) -> None:
        """Create the FTS5 virtual table and sync triggers for the Name table."""
        with self.engine.begin() as conn:
            conn.execute(
                text(
                    "CREATE VIRTUAL TABLE IF NOT EXISTS name_fts "
                    "USING fts5(label, content='name', content_rowid='id')"
                )
            )
            conn.execute(
                text(
                    "CREATE TRIGGER IF NOT EXISTS name_ai AFTER INSERT ON name BEGIN "
                    "INSERT INTO name_fts(rowid, label) VALUES (new.id, new.label); "
                    "END"
                )
            )
            conn.execute(
                text(
                    "CREATE TRIGGER IF NOT EXISTS name_au AFTER UPDATE ON name BEGIN "
                    "INSERT INTO name_fts(name_fts, rowid, label) VALUES ('delete', old.id, old.label); "
                    "INSERT INTO name_fts(rowid, label) VALUES (new.id, new.label); "
                    "END"
                )
            )
            conn.execute(
                text(
                    "CREATE TRIGGER IF NOT EXISTS name_ad AFTER DELETE ON name BEGIN "
                    "INSERT INTO name_fts(name_fts, rowid, label) VALUES ('delete', old.id, old.label); "
                    "END"
                )
            )

    def search_entities(
        self,
        query: str,
        limit: int = 20,
        project_id: int | None = None,
        is_class: bool = False,
    ) -> list[EntityAnnotation]:
        """Search entities by name/synonym using a prefix LIKE match.

        If `is_class` is True, only OWL classes are returned (for class pickers).
        If False (default), only non-class individuals are returned (for annotation search).
        If `project_id` is given, results include:
          - confirmed entities whose ontology is assigned to that project, AND
          - unconfirmed (proposed) entities that belong to that project.
        """
        if not query.strip():
            return []

        pref_en = aliased(EntityName)
        pref_name = aliased(Name)
        match_name = aliased(Name)

        pattern = f"{query.strip()}%"

        stmt = (
            select(
                Entity.curie,
                Entity.type,
                Entity.confirmed,
                pref_name.label.label("preferred_name"),
                func.min(func.length(match_name.label)).label("best_len"),
            )
            .join(EntityName, EntityName.entity_id == Entity.entity_id)
            .join(match_name, match_name.id == EntityName.name_id)
            .outerjoin(
                pref_en,
                (pref_en.entity_id == Entity.entity_id) & pref_en.is_preferred,
            )
            .outerjoin(pref_name, pref_name.id == pref_en.name_id)
            .where(match_name.label.ilike(pattern))
            .where(Entity.is_class == is_class)
            .group_by(Entity.curie, Entity.type, Entity.confirmed, pref_name.label)
            .order_by(func.min(func.length(match_name.label)))
            .limit(limit)
        )

        if project_id is not None:
            stmt = stmt.outerjoin(
                ProjectOntology,
                (ProjectOntology.ontology_id == Entity.ontology_id)
                & (ProjectOntology.project_id == project_id),
            ).where(
                # confirmed entity in one of the project's ontologies
                (ProjectOntology.project_id == project_id)
                # OR proposed entity belonging to this project
                | ((Entity.confirmed == False) & (Entity.project_id == project_id))  # noqa: E712
            )

        with Session(self.engine) as session:
            rows = session.execute(stmt).fetchall()

        return [
            EntityAnnotation(
                entity_id=row.curie,
                preferred_name=row.preferred_name or "",
                kind=row.type,
                confirmed=row.confirmed,
            )
            for row in rows
        ]

    def get_entities_by_curies(self, curies: list[str]) -> list[EntityAnnotation]:
        """Return EntityAnnotation objects for the given CURIE list.

        Entities not found in the database are silently omitted.
        """
        if not curies:
            return []
        pref_en = aliased(EntityName)
        pref_name = aliased(Name)
        stmt = (
            select(
                Entity.curie,
                Entity.type,
                Entity.confirmed,
                pref_name.label.label("preferred_name"),
            )
            .where(Entity.curie.in_(curies))
            .outerjoin(
                pref_en,
                (pref_en.entity_id == Entity.entity_id) & pref_en.is_preferred,
            )
            .outerjoin(pref_name, pref_name.id == pref_en.name_id)
        )
        with Session(self.engine) as session:
            rows = session.execute(stmt).fetchall()
        return [
            EntityAnnotation(
                entity_id=row.curie,
                preferred_name=row.preferred_name or row.curie,
                kind=row.type,
                confirmed=row.confirmed,
            )
            for row in rows
        ]

    def list_proposed_entities(
        self,
        project_id: int,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[dict], int]:
        """Return proposed entities for a project, newest first."""
        pref_en = aliased(EntityName)
        pref_name = aliased(Name)

        base_where = (
            (Entity.confirmed == False)  # noqa: E712
            & (Entity.project_id == project_id)
        )
        stmt = (
            select(
                Entity.entity_id,
                Entity.curie,
                Entity.type,
                Entity.proposed_by,
                Entity.proposal_status,
                Entity.proposed_at,
                pref_name.label.label("preferred_name"),
            )
            .outerjoin(pref_en, (pref_en.entity_id == Entity.entity_id) & pref_en.is_preferred)
            .outerjoin(pref_name, pref_name.id == pref_en.name_id)
            .where(base_where)
        )

        with Session(self.engine) as session:
            total = session.execute(
                select(func.count())
                .select_from(Entity)
                .where(base_where)
            ).scalar_one()

            rows = session.execute(
                stmt.order_by(Entity.proposed_at.desc())
                .limit(limit)
                .offset(offset)
            ).fetchall()

        return [
            {
                "proposal_id": r.entity_id,
                "curie": r.curie,
                "label": r.preferred_name or r.curie,
                "kind": r.type,
                "proposed_by": r.proposed_by,
                "status": r.proposal_status,
                "created_at": r.proposed_at.isoformat() if r.proposed_at else None,
            }
            for r in rows
        ], total

    def store_proposed_entity(
        self,
        project_id: int,
        label: str,
        curie: str,
        kind: str,
        proposed_by: str | None = None,
    ) -> dict:
        """Insert a new proposed entity into the entity table and return it as a dict."""
        now = datetime.now(timezone.utc)
        with Session(self.engine) as session:
            row = Entity(
                curie=curie,
                type=kind,
                confirmed=False,
                project_id=project_id,
                proposed_by=proposed_by,
                proposal_status="pending",
                proposed_at=now,
            )
            session.add(row)
            session.commit()
            session.refresh(row)
            return {
                "proposal_id": row.entity_id,
                "curie": row.curie,
                "label": label,
                "kind": row.type,
                "proposed_by": row.proposed_by,
                "status": row.proposal_status,
                "created_at": row.proposed_at.isoformat() if row.proposed_at else None,
            }

    def list_proposed_properties(
        self,
        project_id: int,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[dict], int]:
        """Return proposed properties for a project, newest first."""
        with Session(self.engine) as session:
            total = session.execute(
                select(func.count())
                .select_from(ProposedProperty)
                .where(ProposedProperty.project_id == project_id)
            ).scalar_one()

            rows = session.execute(
                select(ProposedProperty)
                .where(ProposedProperty.project_id == project_id)
                .order_by(ProposedProperty.created_at.desc())
                .limit(limit)
                .offset(offset)
            ).scalars().all()

        return [
            {
                "proposal_id": r.proposal_id,
                "curie": r.curie,
                "label": r.label,
                "domain_curie": r.domain_curie,
                "range_curie": r.range_curie,
                "proposed_by": r.proposed_by,
                "status": r.status,
                "created_at": r.created_at.isoformat(),
            }
            for r in rows
        ], total

    def store_proposed_property(
        self,
        project_id: int,
        label: str,
        curie: str | None = None,
        domain_curie: str | None = None,
        range_curie: str | None = None,
        proposed_by: str | None = None,
    ) -> dict:
        """Insert a new proposed property and return it as a dict."""
        with Session(self.engine) as session:
            row = ProposedProperty(
                project_id=project_id,
                label=label,
                curie=curie,
                domain_curie=domain_curie,
                range_curie=range_curie,
                proposed_by=proposed_by,
            )
            session.add(row)
            session.commit()
            session.refresh(row)
            return {
                "proposal_id": row.proposal_id,
                "curie": row.curie,
                "label": row.label,
                "domain_curie": row.domain_curie,
                "range_curie": row.range_curie,
                "proposed_by": row.proposed_by,
                "status": row.status,
                "created_at": row.created_at.isoformat(),
            }

    def confirm_entity(self, curie: str) -> None:
        """Promote a proposed entity: set confirmed=True and clear proposal metadata."""
        with Session(self.engine) as session:
            entity = session.scalars(
                select(Entity).where(Entity.curie == curie)
            ).first()
            if entity:
                entity.confirmed = True
                entity.proposal_status = "accepted"
                entity.project_id = None
                session.add(entity)
                session.commit()

    def delete_entity(self, curie: str) -> None:
        """Delete a proposed entity and all referencing rows."""
        with Session(self.engine) as session:
            entity = session.scalars(
                select(Entity).where(Entity.curie == curie)
            ).first()
            if not entity:
                return

            entity_int_id = entity.entity_id

            # Collect relation_ids that reference this entity
            rel_ids: list[int] = list(
                session.scalars(
                    select(Relation.relation_id).where(
                        or_(Relation.subject == curie, Relation.object == curie)
                    )
                )
            )

            # Delete association rows for those relations
            if rel_ids:
                session.execute(
                    sa_delete(StateRelation).where(
                        StateRelation.relation_id.in_(rel_ids)
                    )
                )
                session.execute(
                    sa_delete(SnapshotRelation).where(
                        SnapshotRelation.relation_id.in_(rel_ids)
                    )
                )
                session.execute(
                    sa_delete(UserRelationReference).where(
                        UserRelationReference.relation_id.in_(rel_ids)
                    )
                )
                session.execute(
                    sa_delete(Relation).where(Relation.relation_id.in_(rel_ids))
                )

            # Delete pointer association rows then pointers
            session.execute(
                sa_delete(StatePointer).where(StatePointer.entity_id == curie)
            )
            session.execute(
                sa_delete(SnapshotPointer).where(
                    SnapshotPointer.entity_id == curie
                )
            )
            session.execute(
                sa_delete(Pointer).where(Pointer.entity_id == curie)
            )

            # Delete entity names (collect name_ids first for orphan cleanup)
            name_ids: list[int] = list(
                session.scalars(
                    select(EntityName.name_id).where(
                        EntityName.entity_id == entity_int_id
                    )
                )
            )
            session.execute(
                sa_delete(EntityName).where(
                    EntityName.entity_id == entity_int_id
                )
            )
            if name_ids:
                still_used = set(
                    session.scalars(
                        select(EntityName.name_id).where(
                            EntityName.name_id.in_(name_ids)
                        )
                    )
                )
                orphaned = [n for n in name_ids if n not in still_used]
                if orphaned:
                    session.execute(
                        sa_delete(Name).where(Name.id.in_(orphaned))
                    )

            session.execute(
                sa_delete(Entity).where(Entity.entity_id == entity_int_id)
            )
            session.commit()

        self.rebuild_fts()

    def update_entity_curie(self, old_curie: str, new_curie: str) -> None:
        """Rename an entity's CURIE, updating all FK-referencing tables."""
        with Session(self.engine) as session:
            # Disable FK checks for the duration of the rename
            session.execute(text("PRAGMA foreign_keys = OFF"))
            session.execute(
                text("UPDATE entity SET curie = :new WHERE curie = :old"),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(
                text(
                    "UPDATE pointer SET entity_id = :new WHERE entity_id = :old"
                ),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(
                text(
                    "UPDATE state_pointer SET entity_id = :new WHERE entity_id = :old"
                ),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(
                text(
                    "UPDATE snapshot_pointer SET entity_id = :new WHERE entity_id = :old"
                ),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(
                text("UPDATE relation SET subject = :new WHERE subject = :old"),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(
                text("UPDATE relation SET object = :new WHERE object = :old"),
                {"new": new_curie, "old": old_curie},
            )
            session.execute(text("PRAGMA foreign_keys = ON"))
            session.commit()

    def store_annotation(self, ann: ReferenceAnnotation) -> None:
        """Persist an annotation state to the database.

        Stores the reference, pointers (entities must already exist), relations,
        and records a new AnnotationState with associated StatePointer /
        StateRelation rows. If ``ann.completed`` is True an AnnotationSnapshot
        is also recorded.
        """
        reference_id = self.store_reference(ann.reference)

        for pointer in ann.pointers:
            pointer.reference_id = reference_id

        content_hash = _content_hash(ann.pointers, ann.relations)
        now = datetime.now(timezone.utc)

        with Session(self.engine, autoflush=False) as session:
            # Upsert entities before inserting pointers.
            for entity in ann.entities:
                if not entity.confirmed:
                    # Proposed (annotator-coined) entities live in the entity table
                    # with confirmed=False and project-scoping metadata.
                    # on_conflict_do_update with a no-op set lets us always get the
                    # entity_id back (needed to link Name rows), while leaving existing
                    # rows unchanged on re-save.
                    int_entity_id = session.execute(
                        insert(Entity)
                        .values(
                            curie=entity.entity_id,
                            type=entity.kind,
                            confirmed=False,
                            project_id=ann.project_id,
                            proposal_status="pending",
                            proposed_at=now,
                        )
                        .on_conflict_do_update(
                            index_elements=["curie"],
                            set_={"type": Entity.type},  # no-op; keeps existing row
                        )
                        .returning(Entity.entity_id)
                    ).scalar_one()

                    # Store preferred_name so the entity is searchable and the
                    # admin listing has a meaningful label.
                    trimmed = entity.preferred_name.strip()
                    if trimmed:
                        name_id = session.execute(
                            insert(Name)
                            .values(label=trimmed)
                            .on_conflict_do_update(
                                index_elements=["label"],
                                set_={"label": Name.label},
                            )
                            .returning(Name.id)
                        ).scalar_one()
                        session.execute(
                            insert(EntityName)
                            .values(
                                entity_id=int_entity_id,
                                name_id=name_id,
                                is_preferred=True,
                            )
                            .on_conflict_do_update(
                                index_elements=["entity_id", "name_id"],
                                set_={"is_preferred": True},
                            )
                        )
                    continue

                # Confirmed (ontology) entity — upsert into entity table.
                int_entity_id = session.execute(
                    insert(Entity)
                    .values(
                        curie=entity.entity_id,
                        type=entity.kind,
                        confirmed=True,
                    )
                    .on_conflict_do_update(
                        index_elements=["curie"],
                        set_={"type": Entity.type},  # confirmed intentionally omitted
                    )
                    .returning(Entity.entity_id)
                ).scalar_one()

                # Upsert all names (preferred + synonyms) into Name table,
                # then link via EntityName.
                # Exclude any synonym equal to the preferred name so the
                # preferred flag is never overwritten to False.
                all_names = [(entity.preferred_name, True)] + [
                    (s, False)
                    for s in entity.synonyms
                    if s != entity.preferred_name
                ]
                for label, is_preferred in all_names:
                    name_id = session.execute(
                        insert(Name)
                        .values(label=label)
                        .on_conflict_do_update(
                            index_elements=["label"],
                            set_={"label": Name.label},
                        )
                        .returning(Name.id)
                    ).scalar_one()
                    session.execute(
                        insert(EntityName)
                        .values(
                            entity_id=int_entity_id,
                            name_id=name_id,
                            is_preferred=is_preferred,
                        )
                        .on_conflict_do_update(
                            index_elements=["entity_id", "name_id"],
                            set_={"is_preferred": is_preferred},
                        )
                    )

            session.flush()

            # Store pointers.
            for pointer in ann.pointers:
                session.execute(
                    insert(Pointer)
                    .values(
                        reference_id=pointer.reference_id,
                        entity_id=pointer.entity_id,
                        offset=pointer.offset,
                        length=pointer.length,
                        field=pointer.field,
                        exact_text=pointer.exact_text,
                        prefix_text=pointer.prefix_text,
                        suffix_text=pointer.suffix_text,
                    )
                    .on_conflict_do_update(
                        index_elements=["reference_id", "entity_id", "offset", "length", "field"],
                        set_={
                            "exact_text": pointer.exact_text,
                            "prefix_text": pointer.prefix_text,
                            "suffix_text": pointer.suffix_text,
                        },
                    )
                )

            session.flush()

            # Store relations and UserRelationReference entries.
            relation_ids: list[int] = []
            for relmodel in ann.relations:
                relation_id = session.execute(
                    insert(Relation)
                    .values(relmodel.model_dump(exclude_none=True))
                    .on_conflict_do_update(
                        index_elements=["predicate", "subject", "object"],
                        set_={
                            "predicate": Relation.predicate,
                            "subject": Relation.subject,
                            "object": Relation.object,
                        },
                    )
                    .returning(Relation.relation_id)
                ).scalar_one()
                relation_ids.append(relation_id)
                session.execute(
                    insert(UserRelationReference)
                    .values(
                        UserRelationReference(
                            user_id=ann.user.user_id,
                            reference_id=reference_id,
                            relation_id=relation_id,
                        ).model_dump()
                    )
                    .on_conflict_do_nothing()
                )

            # Record the annotation state.
            state_id = session.execute(
                insert(AnnotationState)
                .values(
                    project_id=ann.project_id,
                    user_id=ann.user.user_id,
                    reference_id=reference_id,
                    content_hash=content_hash,
                    recorded_at=now,
                )
                .returning(AnnotationState.state_id)
            ).scalar_one()

            for pointer in ann.pointers:
                session.execute(
                    insert(StatePointer)
                    .values(
                        state_id=state_id,
                        reference_id=pointer.reference_id,
                        entity_id=pointer.entity_id,
                        offset=pointer.offset,
                        length=pointer.length,
                        field=pointer.field,
                    )
                    .on_conflict_do_nothing()
                )

            for relation_id in relation_ids:
                session.execute(
                    insert(StateRelation)
                    .values(state_id=state_id, relation_id=relation_id)
                    .on_conflict_do_nothing()
                )

            # Optionally record an immutable snapshot.
            if ann.completed:
                snapshot_id = session.execute(
                    insert(AnnotationSnapshot)
                    .values(
                        project_id=ann.project_id,
                        user_id=ann.user.user_id,
                        reference_id=reference_id,
                        content_hash=content_hash,
                        created_at=now,
                    )
                    .returning(AnnotationSnapshot.snapshot_id)
                ).scalar_one()

                for pointer in ann.pointers:
                    session.execute(
                        insert(SnapshotPointer)
                        .values(
                            snapshot_id=snapshot_id,
                            reference_id=pointer.reference_id,
                            entity_id=pointer.entity_id,
                            offset=pointer.offset,
                            length=pointer.length,
                            field=pointer.field,
                        )
                        .on_conflict_do_nothing()
                    )

                for relation_id in relation_ids:
                    session.execute(
                        insert(SnapshotRelation)
                        .values(
                            snapshot_id=snapshot_id, relation_id=relation_id
                        )
                        .on_conflict_do_nothing()
                    )

            session.commit()

    def store_reference(self, reference: Reference) -> int:
        """Store reference and return its primary key.

        Upserts by pubmed_id when set, else by doi when set, else plain insert.
        reference_id is always excluded from the INSERT so that the DB
        auto-assigns a fresh PK for new rows; existing rows are matched on the
        natural identifier and left otherwise unchanged.
        """
        data = reference.model_dump(exclude={"reference_id"}, exclude_none=True)

        if reference.pubmed_id is not None:
            conflict_target = ["pubmed_id"]
        elif reference.doi is not None:
            conflict_target = ["doi"]
        else:
            conflict_target = None

        with Session(self.engine) as session:
            if conflict_target:
                stmt = (
                    insert(Reference)
                    .values(data)
                    .on_conflict_do_update(
                        index_elements=conflict_target,
                        set_={conflict_target[0]: data[conflict_target[0]]},
                    )
                    .returning(Reference.reference_id)
                )
            else:
                stmt = insert(Reference).values(data).returning(Reference.reference_id)

            ref_id: int = session.scalar(stmt)
            session.commit()

        return ref_id

    def store_item(self, item: User | Entity | Reference | Pointer) -> None:
        """Store ``item`` into the database in accordance to its model class."""
        with Session(self.engine) as session:
            session.execute(
                insert(item.__class__)
                .values(item.model_dump(exclude_none=True))
                .on_conflict_do_nothing()
            )
            session.commit()

    def store_items(self, items: Iterable[SQLModel]) -> None:
        """Store ``items`` into the database in accordance to their model class."""
        models: dict = {}
        for item in items:
            models.setdefault(item.__class__, []).append(item)

        with Session(self.engine) as session:
            for item in itertools.chain(
                *(
                    models.get(key, [])
                    for key in (User, Entity, Reference, Pointer)
                )
            ):
                session.execute(
                    insert(item.__class__)
                    .values(item.model_dump(exclude_none=True))
                    .on_conflict_do_nothing()
                )
            session.commit()

    def get_article_by_pubmed_id(self, pubmed_id: int) -> Reference:
        with Session(self.engine) as session:
            return session.scalar(
                select(Reference).where(Reference.pubmed_id == pubmed_id)
            )

    def get_reference_by_doi(self, doi: str) -> Reference | None:
        with Session(self.engine) as session:
            return session.scalar(
                select(Reference).where(Reference.doi == doi)
            )

    def get_project_reference_ids(self, project_id: int) -> set[int]:
        with Session(self.engine) as session:
            rows = session.scalars(
                select(ProjectReference.reference_id).where(
                    ProjectReference.project_id == project_id
                )
            )
            return set(rows)

    def list_project_references(self, project_id: int) -> list[Reference]:
        with Session(self.engine) as session:
            return list(
                session.scalars(
                    select(Reference)
                    .join(ProjectReference, Reference.reference_id == ProjectReference.reference_id)
                    .where(ProjectReference.project_id == project_id)
                    .order_by(Reference.year.desc(), Reference.reference_id.desc())
                )
            )

    def store_relations(
        self, user: UUID, reference: int, relations: Iterable[Relation]
    ) -> None:
        with Session(self.engine) as session:
            for relmodel in relations:
                relation_id = session.execute(
                    insert(Relation)
                    .values(relmodel.model_dump(exclude_none=True))
                    .on_conflict_do_update(
                        index_elements=["predicate", "subject", "object"],
                        set_={
                            "predicate": Relation.predicate,
                            "subject": Relation.subject,
                            "object": Relation.object,
                        },
                    )
                    .returning(Relation.relation_id)
                ).scalar_one()
                session.execute(
                    insert(UserRelationReference)
                    .values(
                        UserRelationReference(
                            user_id=user,
                            reference_id=reference,
                            relation_id=relation_id,
                        ).model_dump()
                    )
                    .on_conflict_do_nothing()
                )
            session.commit()

    def get_user(self, email: str) -> User | None:
        with Session(self.engine) as session:
            return session.scalar(select(User).where(User.email == email))

    def get_user_auth(self, user_id: UUID) -> UserAuth | None:
        with Session(self.engine) as session:
            return session.scalar(
                select(UserAuth).where(UserAuth.user_id == user_id)
            )

    def create_user(
        self,
        user: User,
        password: str,
        is_super_user: bool = False,
        can_manage: bool = False,
    ) -> UUID | None:
        with Session(self.engine) as session:
            user_id: UUID | None = session.scalar(
                insert(User)
                .values(user.model_dump(exclude_none=True))
                .on_conflict_do_nothing()
                .returning(User.user_id)
            )
            user_auth = UserAuth(
                user_id=user_id,
                hashed_password=hash_password(password),
                is_super_user=is_super_user,
                can_manage=can_manage,
            )
            session.execute(
                insert(UserAuth)
                .values(user_auth.model_dump())
                .on_conflict_do_nothing()
            )
            session.commit()

        return user_id

    def update_password(self, user_id: UUID, new_password: str) -> None:
        with Session(self.engine) as session:
            user_auth = session.scalar(
                select(UserAuth).where(UserAuth.user_id == user_id)
            )
            if user_auth is None:
                raise ValueError(f"No user_auth found for user_id {user_id}")
            user_auth.hashed_password = hash_password(new_password)
            session.add(user_auth)
            session.commit()

    # ------------------------------------------------------------------
    # Project management
    # ------------------------------------------------------------------

    def create_project(
        self,
        name: str,
        description: str | None = None,
        required_annotators: int = 2,
    ) -> int:
        """Create a new project and return its ``project_id``.

        :param name: Human-readable project name.
        :param description: Optional free-text description.
        :param required_annotators: Completions required before a reference
            becomes available for curation. Default 2.
        """
        with Session(self.engine) as session:
            project_id: int = session.execute(
                insert(Project)
                .values(
                    name=name,
                    description=description,
                    required_annotators=required_annotators,
                )
                .returning(Project.project_id)
            ).scalar_one()
            session.commit()
        return project_id

    def get_project(self, project_id: int) -> Project | None:
        """Return the :class:`Project` with the given id, or ``None``."""
        with Session(self.engine) as session:
            return session.get(Project, project_id)

    def list_projects(self) -> list[Project]:
        """Return all projects."""
        with Session(self.engine) as session:
            return list(session.scalars(select(Project)).all())

    def list_user_projects(self, user_id: UUID) -> list[Project]:
        """Return all projects the user has any membership role in."""
        with Session(self.engine) as session:
            return list(
                session.scalars(
                    select(Project)
                    .join(
                        ProjectMembership,
                        ProjectMembership.project_id == Project.project_id,
                    )
                    .where(ProjectMembership.user_id == user_id)
                    .distinct()
                ).all()
            )

    # ------------------------------------------------------------------
    # Project membership
    # ------------------------------------------------------------------

    def is_project_creator(self, user_id: UUID) -> bool:
        """Return True if the user has the ``can_manage`` permission flag.

        :param user_id: User to check.
        """
        with Session(self.engine) as session:
            auth = session.get(UserAuth, user_id)
            return auth is not None and auth.can_manage

    def add_project_member(
        self, project_id: int, user_id: UUID, role: str
    ) -> None:
        """Assign ``role`` to ``user_id`` in ``project_id``.

        :param role: One of ``"manager"``, ``"annotator"``, ``"curator"``.
        """
        with Session(self.engine) as session:
            session.execute(
                insert(ProjectMembership)
                .values(project_id=project_id, user_id=user_id, role=role)
                .on_conflict_do_nothing()
            )
            session.commit()

    def remove_project_member(
        self, project_id: int, user_id: UUID, role: str
    ) -> None:
        """Remove a specific role from a user within a project."""
        with Session(self.engine) as session:
            session.execute(
                sa_delete(ProjectMembership).where(
                    (ProjectMembership.project_id == project_id)
                    & (ProjectMembership.user_id == user_id)
                    & (ProjectMembership.role == role)
                )
            )
            session.commit()

    def get_project_members(
        self, project_id: int
    ) -> list[tuple[User, list[str]]]:
        """Return all members of a project with their assigned roles.

        :returns: List of ``(User, [role, ...])`` tuples.
        """
        with Session(self.engine) as session:
            rows = session.execute(
                select(ProjectMembership.user_id, ProjectMembership.role).where(
                    ProjectMembership.project_id == project_id
                )
            ).all()
            user_roles: dict[UUID, list[str]] = {}
            for uid, role in rows:
                user_roles.setdefault(uid, []).append(role)
            result = []
            for uid, roles in user_roles.items():
                user = session.get(User, uid)
                if user is not None:
                    result.append((user, roles))
            return result

    def get_user_project_roles(
        self, user_id: UUID, project_id: int
    ) -> list[str]:
        """Return all roles ``user_id`` holds in ``project_id``."""
        with Session(self.engine) as session:
            return list(
                session.scalars(
                    select(ProjectMembership.role).where(
                        (ProjectMembership.user_id == user_id)
                        & (ProjectMembership.project_id == project_id)
                    )
                ).all()
            )

    # ------------------------------------------------------------------
    # Project ontologies and references
    # ------------------------------------------------------------------

    def assign_ontology_to_project(
        self, project_id: int, ontology_id: int
    ) -> None:
        """Make an ontology available for annotation in a project."""
        with Session(self.engine) as session:
            session.execute(
                insert(ProjectOntology)
                .values(project_id=project_id, ontology_id=ontology_id)
                .on_conflict_do_nothing()
            )
            session.commit()

    def get_project_ontologies(self, project_id: int) -> list[Ontology]:
        """Return all ontologies assigned to a project."""
        with Session(self.engine) as session:
            return list(
                session.scalars(
                    select(Ontology)
                    .join(ProjectOntology, Ontology.ontology_id == ProjectOntology.ontology_id)
                    .where(ProjectOntology.project_id == project_id)
                )
            )

    def remove_ontology_from_project(
        self, project_id: int, ontology_id: int
    ) -> None:
        """Remove an ontology from a project."""
        with Session(self.engine) as session:
            session.execute(
                sa_delete(ProjectOntology).where(
                    (ProjectOntology.project_id == project_id)
                    & (ProjectOntology.ontology_id == ontology_id)
                )
            )
            session.commit()

    def add_reference_to_project(
        self, project_id: int, reference_id: int
    ) -> None:
        """Add a reference to a project's annotation queue."""
        with Session(self.engine) as session:
            session.execute(
                insert(ProjectReference)
                .values(project_id=project_id, reference_id=reference_id)
                .on_conflict_do_nothing()
            )
            session.commit()

    def remove_reference_from_project(
        self, project_id: int, reference_id: int
    ) -> None:
        """Remove a reference from a project."""
        with Session(self.engine) as session:
            session.execute(
                sa_delete(ProjectReference).where(
                    (ProjectReference.project_id == project_id)
                    & (ProjectReference.reference_id == reference_id)
                )
            )
            session.commit()

    # ------------------------------------------------------------------
    # Last-active project
    # ------------------------------------------------------------------

    def get_user_last_project(self, user_id: UUID) -> int | None:
        """Return the ``project_id`` of the user's last active project."""
        with Session(self.engine) as session:
            row = session.get(UserLastProject, user_id)
            return row.project_id if row is not None else None

    def set_user_last_project(self, user_id: UUID, project_id: int) -> None:
        """Record ``project_id`` as the user's last active project."""
        with Session(self.engine) as session:
            session.execute(
                insert(UserLastProject)
                .values(user_id=user_id, project_id=project_id)
                .on_conflict_do_update(
                    index_elements=["user_id"],
                    set_={"project_id": project_id},
                )
            )
            session.commit()

    # ------------------------------------------------------------------
    # Project-scoped annotation queue
    # ------------------------------------------------------------------

    def get_project_annotation_queue(
        self, project_id: int, user_id: UUID
    ) -> list[str]:
        """Return identifiers of references in the project not yet completed
        by the user.

        :returns: PubMed ID strings where available, otherwise DOIs.
        """
        with Session(self.engine) as session:
            completed = select(AnnotationSnapshot.reference_id).where(
                (AnnotationSnapshot.project_id == project_id)
                & (AnnotationSnapshot.user_id == user_id)
            )
            stmt = (
                select(Reference.pubmed_id, Reference.doi)
                .join(
                    ProjectReference,
                    ProjectReference.reference_id == Reference.reference_id,
                )
                .where(ProjectReference.project_id == project_id)
                .where(Reference.reference_id.not_in(completed))
            )
            return [
                str(pubmed_id) if pubmed_id is not None else doi
                for pubmed_id, doi in session.execute(stmt).all()
            ]

    # ------------------------------------------------------------------
    # Curation
    # ------------------------------------------------------------------

    def get_curation_queue(self, project_id: int) -> list[Reference]:
        """Return references in the project that have reached the required
        number of completed annotator snapshots and are ready for curation.
        """
        with Session(self.engine) as session:
            project = session.get(Project, project_id)
            if project is None:
                return []
            threshold = project.required_annotators
            subq = (
                select(AnnotationSnapshot.reference_id)
                .where(AnnotationSnapshot.project_id == project_id)
                .group_by(AnnotationSnapshot.reference_id)
                .having(
                    func.count(func.distinct(AnnotationSnapshot.user_id))
                    >= threshold
                )
                .subquery()
            )
            return list(
                session.scalars(
                    select(Reference).join(
                        subq, subq.c.reference_id == Reference.reference_id
                    )
                ).all()
            )

    def get_annotator_snapshots(
        self, project_id: int, reference_id: int
    ) -> list[AnnotatorSnapshot]:
        """Return the completed annotation snapshots for all annotators on a
        reference within a project.

        Used by the curation view to compare annotations across annotators
        and flag disagreements.
        """
        with Session(self.engine) as session:
            all_snaps = list(
                session.scalars(
                    select(AnnotationSnapshot)
                    .where(AnnotationSnapshot.project_id == project_id)
                    .where(AnnotationSnapshot.reference_id == reference_id)
                    .order_by(AnnotationSnapshot.snapshot_id)
                ).all()
            )
            # Keep only the latest snapshot per user (highest snapshot_id).
            latest: dict[UUID, AnnotationSnapshot] = {}
            for s in all_snaps:
                latest[s.user_id] = s
            snapshots = list(latest.values())
            result = []
            for snap in snapshots:
                user = session.get(User, snap.user_id)
                if user is None:
                    continue
                pointers = list(
                    session.scalars(
                        select(Pointer)
                        .join(
                            SnapshotPointer,
                            (Pointer.reference_id == SnapshotPointer.reference_id)
                            & (Pointer.entity_id == SnapshotPointer.entity_id)
                            & (Pointer.offset == SnapshotPointer.offset)
                            & (Pointer.length == SnapshotPointer.length)
                            & (Pointer.field == SnapshotPointer.field),
                        )
                        .where(SnapshotPointer.snapshot_id == snap.snapshot_id)
                    ).all()
                )
                relation_ids = list(
                    session.scalars(
                        select(SnapshotRelation.relation_id).where(
                            SnapshotRelation.snapshot_id == snap.snapshot_id
                        )
                    ).all()
                )
                relations = (
                    list(
                        session.scalars(
                            select(Relation).where(
                                Relation.relation_id.in_(relation_ids)
                            )
                        ).all()
                    )
                    if relation_ids
                    else []
                )
                result.append(
                    AnnotatorSnapshot(
                        user=user,
                        reference_id=reference_id,
                        pointers=pointers,
                        relations=relations,
                        created_at=snap.created_at,
                    )
                )
            return result

    def save_curated_annotation(
        self,
        project_id: int,
        reference_id: int,
        curator_id: UUID,
        pointers: list[Pointer],
        relations: list[Relation],
    ) -> int:
        """Persist a curator's curated annotation, replacing any previous one.

        :returns: The ``curated_id`` of the stored record.
        """
        content_hash = _content_hash(pointers, relations)
        now = datetime.now(timezone.utc)
        with Session(self.engine) as session:
            existing = session.scalar(
                select(CuratedAnnotation)
                .where(CuratedAnnotation.project_id == project_id)
                .where(CuratedAnnotation.reference_id == reference_id)
                .where(CuratedAnnotation.curator_id == curator_id)
            )
            if existing is not None:
                session.execute(
                    sa_delete(CuratedAnnotationPointer).where(
                        CuratedAnnotationPointer.curated_id == existing.curated_id
                    )
                )
                session.execute(
                    sa_delete(CuratedAnnotationRelation).where(
                        CuratedAnnotationRelation.curated_id == existing.curated_id
                    )
                )
                session.execute(
                    sa_delete(CuratedAnnotation).where(
                        CuratedAnnotation.curated_id == existing.curated_id
                    )
                )
            curated_id: int = session.execute(
                insert(CuratedAnnotation)
                .values(
                    project_id=project_id,
                    reference_id=reference_id,
                    curator_id=curator_id,
                    content_hash=content_hash,
                    created_at=now,
                )
                .returning(CuratedAnnotation.curated_id)
            ).scalar_one()
            for pointer in pointers:
                session.execute(
                    insert(CuratedAnnotationPointer)
                    .values(
                        curated_id=curated_id,
                        reference_id=pointer.reference_id,
                        entity_id=pointer.entity_id,
                        offset=pointer.offset,
                        length=pointer.length,
                        field=pointer.field,
                    )
                    .on_conflict_do_nothing()
                )
            for rel in relations:
                relation_id: int = session.execute(
                    insert(Relation)
                    .values(rel.model_dump(exclude_none=True))
                    .on_conflict_do_update(
                        index_elements=["predicate", "subject", "object"],
                        set_={
                            "predicate": Relation.predicate,
                            "subject": Relation.subject,
                            "object": Relation.object,
                        },
                    )
                    .returning(Relation.relation_id)
                ).scalar_one()
                session.execute(
                    insert(CuratedAnnotationRelation)
                    .values(curated_id=curated_id, relation_id=relation_id)
                    .on_conflict_do_nothing()
                )
            session.commit()
        return curated_id

    def get_curated_annotation(
        self, project_id: int, reference_id: int, curator_id: UUID
    ) -> AnnotatorSnapshot | None:
        """Return a curator's curated annotation as an :class:`AnnotatorSnapshot`,
        or ``None`` if it does not exist yet.
        """
        with Session(self.engine) as session:
            curated = session.scalar(
                select(CuratedAnnotation)
                .where(CuratedAnnotation.project_id == project_id)
                .where(CuratedAnnotation.reference_id == reference_id)
                .where(CuratedAnnotation.curator_id == curator_id)
            )
            if curated is None:
                return None
            curator = session.get(User, curator_id)
            if curator is None:
                return None
            pointers = list(
                session.scalars(
                    select(Pointer)
                    .join(
                        CuratedAnnotationPointer,
                        (Pointer.reference_id == CuratedAnnotationPointer.reference_id)
                        & (Pointer.entity_id == CuratedAnnotationPointer.entity_id)
                        & (Pointer.offset == CuratedAnnotationPointer.offset)
                        & (Pointer.length == CuratedAnnotationPointer.length)
                        & (Pointer.field == CuratedAnnotationPointer.field),
                    )
                    .where(
                        CuratedAnnotationPointer.curated_id == curated.curated_id
                    )
                ).all()
            )
            relation_ids = list(
                session.scalars(
                    select(CuratedAnnotationRelation.relation_id).where(
                        CuratedAnnotationRelation.curated_id == curated.curated_id
                    )
                ).all()
            )
            relations = (
                list(
                    session.scalars(
                        select(Relation).where(
                            Relation.relation_id.in_(relation_ids)
                        )
                    ).all()
                )
                if relation_ids
                else []
            )
            return AnnotatorSnapshot(
                user=curator,
                reference_id=reference_id,
                pointers=pointers,
                relations=relations,
                created_at=curated.created_at,
            )

    def get_relation(
        self, predicate: str, subject: str, object: str
    ) -> Relation | None:
        with Session(self.engine) as session:
            return session.execute(
                select(Relation)
                .where(Relation.subject == subject)
                .where(Relation.object == object)
                .where(Relation.predicate == predicate)
            ).scalar_one_or_none()

    def get_reference_annotation(
        self, pubmed_id: int, user_id: UUID, project_id: int
    ) -> ReferenceAnnotation:
        """Retrieve reference annotation from the database.

        Returns the annotation corresponding to the latest AnnotationState for
        the given (project, user, reference) triple. ``completed`` is True when
        the latest state's content hash matches the most recent
        AnnotationSnapshot for the same triple.

        :param pubmed_id: PubMed id to retrieve with annotations from the db.
        :param user_id: User id to retrieve annotations for.
        :param project_id: Project the annotation belongs to.
        :return: ReferenceAnnotation model for ``pubmed_id`` and ``user_id``.
        :raises ValueError: If reference or user not found.
        """
        with Session(self.engine) as session:
            reference = session.scalar(
                select(Reference).where(Reference.pubmed_id == pubmed_id)
            )
            if reference is None:
                raise ValueError(
                    f"Reference with pubmed_id {pubmed_id} not found"
                )

            user = session.get(User, user_id)
            if user is None:
                raise ValueError(f"User with user_id {user_id} not found")

            # Latest state for this (project, user, reference) triple.
            latest_state = session.scalar(
                select(AnnotationState)
                .where(AnnotationState.project_id == project_id)
                .where(AnnotationState.user_id == user_id)
                .where(AnnotationState.reference_id == reference.reference_id)
                .order_by(AnnotationState.state_id.desc())
                .limit(1)
            )

            if latest_state is None:
                return ReferenceAnnotation(
                    project_id=project_id,
                    user=User.model_validate(user),
                    reference=Reference.model_validate(reference),
                    pointers=[],
                    relations=[],
                    completed=False,
                    last_updated=datetime.now(timezone.utc),
                )

            # Load pointers via JOIN with StatePointer.
            pointers = list(
                session.scalars(
                    select(Pointer)
                    .join(
                        StatePointer,
                        (Pointer.reference_id == StatePointer.reference_id)
                        & (Pointer.entity_id == StatePointer.entity_id)
                        & (Pointer.offset == StatePointer.offset)
                        & (Pointer.length == StatePointer.length)
                        & (Pointer.field == StatePointer.field),
                    )
                    .where(StatePointer.state_id == latest_state.state_id)
                )
            )

            # Load the entities referenced by those pointers.
            # Pointer.entity_id stores the CURIE; Entity is looked up by curie.
            entity_curies = {p.entity_id for p in pointers}
            entities: list[EntityAnnotation] = []
            if entity_curies:
                rows = list(
                    session.scalars(
                        select(Entity).where(Entity.curie.in_(entity_curies))
                    )
                )
                for entity in rows:
                    # Preferred name: EntityName row with is_preferred=True.
                    preferred_name = (
                        session.scalar(
                            select(Name.label)
                            .join(EntityName, Name.id == EntityName.name_id)
                            .where(EntityName.entity_id == entity.entity_id)
                            .where(EntityName.is_preferred.is_(True))
                        )
                        or ""
                    )

                    # Synonyms: all other EntityName rows.
                    synonyms = list(
                        session.scalars(
                            select(Name.label)
                            .join(EntityName, Name.id == EntityName.name_id)
                            .where(EntityName.entity_id == entity.entity_id)
                            .where(EntityName.is_preferred.is_(False))
                        )
                    )
                    entities.append(
                        EntityAnnotation(
                            entity_id=entity.curie,
                            preferred_name=preferred_name,
                            kind=entity.type,
                            synonyms=synonyms,
                            confirmed=entity.confirmed,
                            is_class=entity.is_class,
                        )
                    )

            # Load relations via JOIN with StateRelation.
            relations = list(
                session.scalars(
                    select(Relation)
                    .join(
                        StateRelation,
                        Relation.relation_id == StateRelation.relation_id,
                    )
                    .where(StateRelation.state_id == latest_state.state_id)
                )
            )

            # Completed when the latest snapshot for this (project, user,
            # reference) triple has the same content hash.
            latest_snapshot = session.scalar(
                select(AnnotationSnapshot)
                .where(AnnotationSnapshot.project_id == project_id)
                .where(AnnotationSnapshot.user_id == user_id)
                .where(
                    AnnotationSnapshot.reference_id == reference.reference_id
                )
                .order_by(AnnotationSnapshot.snapshot_id.desc())
                .limit(1)
            )
            completed = (
                latest_snapshot is not None
                and latest_snapshot.content_hash == latest_state.content_hash
            )

            return ReferenceAnnotation(
                project_id=project_id,
                user=User.model_validate(user),
                reference=Reference.model_validate(reference),
                entities=entities,
                pointers=pointers,
                relations=relations,
                completed=completed,
                last_updated=latest_state.recorded_at,
            )

    # -------------------------------------------------------------------------
    # Ontology management
    # -------------------------------------------------------------------------

    def store_ontology(
        self,
        name: str,
        prefix: str,
        uri: str,
        version: str | None = None,
    ) -> int:
        """Create or update an Ontology record. Returns ``ontology_id``.

        Conflicts are resolved on ``prefix``, which must be unique.
        """
        with Session(self.engine) as session:
            ontology_id: int = session.execute(
                insert(Ontology)
                .values(name=name, prefix=prefix, uri=uri, version=version)
                .on_conflict_do_update(
                    index_elements=["prefix"],
                    set_={
                        "name": Ontology.name,
                        "uri": Ontology.uri,
                        "version": Ontology.version,
                    },
                )
                .returning(Ontology.ontology_id)
            ).scalar_one()
            session.commit()
        return ontology_id

    def load_ontology_entities(
        self,
        ontology_id: int,
        entities: Iterable[EntityAnnotation],
        batch_size: int = 500,
    ) -> int:
        """Bulk-load entities from an ontology into the database.

        Each entity's ``entity_id`` field is treated as the CURIE. Names and
        synonyms are upserted into the ``Name`` / ``EntityName`` tables.

        Rows are committed in batches of ``batch_size`` for memory efficiency.
        The FTS5 index is rebuilt once at the end, which is much faster than
        relying on per-row triggers for large ontologies.

        Returns the total number of entities processed.
        """
        total = 0
        batch: list[EntityAnnotation] = []
        for entity in entities:
            batch.append(entity)
            if len(batch) >= batch_size:
                self._load_entity_batch(ontology_id, batch)
                total += len(batch)
                batch = []
        if batch:
            self._load_entity_batch(ontology_id, batch)
            total += len(batch)
        if total:
            self.rebuild_fts()
        return total

    def _load_entity_batch(
        self, ontology_id: int, entities: list[EntityAnnotation]
    ) -> None:
        with Session(self.engine) as session:
            for entity in entities:
                int_entity_id: int = session.execute(
                    insert(Entity)
                    .values(
                        curie=entity.entity_id,
                        type=entity.kind,
                        ontology_id=ontology_id,
                        is_class=entity.is_class,
                    )
                    .on_conflict_do_update(
                        index_elements=["curie"],
                        set_={
                            "type": Entity.type,
                            "ontology_id": Entity.ontology_id,
                            "is_class": entity.is_class,
                        },
                    )
                    .returning(Entity.entity_id)
                ).scalar_one()

                all_names: list[tuple[str, bool]] = [
                    (entity.preferred_name, True)
                ] + [(s, False) for s in entity.synonyms]

                for label, is_preferred in all_names:
                    name_id: int = session.execute(
                        insert(Name)
                        .values(label=label)
                        .on_conflict_do_update(
                            index_elements=["label"],
                            set_={"label": Name.label},
                        )
                        .returning(Name.id)
                    ).scalar_one()
                    session.execute(
                        insert(EntityName)
                        .values(
                            entity_id=int_entity_id,
                            name_id=name_id,
                            is_preferred=is_preferred,
                        )
                        .on_conflict_do_update(
                            index_elements=["entity_id", "name_id"],
                            set_={"is_preferred": is_preferred},
                        )
                    )
            session.commit()

    def rebuild_fts(self) -> None:
        """Rebuild the FTS5 name index from the current Name table contents.

        Call this after any bulk data manipulation that bypassed the row-level
        sync triggers (e.g. after ``load_ontology_entities``).
        """
        with self.engine.begin() as conn:
            conn.execute(
                text("INSERT INTO name_fts(name_fts) VALUES ('rebuild')")
            )

    def load_ontology_triples(self, triples: list[ParsedTriple]) -> int:
        """Load ontology triples into the Triple table.

        Resolves CURIE strings to integer entity PKs. Triples whose subject
        or object CURIE is not found in the Entity table are silently skipped
        (this can happen when an ontology imports terms from another ontology
        that has not yet been loaded).

        Returns the number of triples stored.
        """
        if not triples:
            return 0

        with Session(self.engine) as session:
            # Resolve all referenced CURIEs to integer entity IDs in one query
            all_curies = {t.subject_curie for t in triples} | {
                t.object_curie for t in triples if t.object_curie
            }
            curie_to_id: dict[str, int] = dict(
                session.execute(
                    select(Entity.curie, Entity.entity_id).where(
                        Entity.curie.in_(all_curies)
                    )
                ).fetchall()
            )

            count = 0
            for triple in triples:
                subject_id = curie_to_id.get(triple.subject_curie)
                if subject_id is None:
                    continue
                object_id = (
                    curie_to_id.get(triple.object_curie)
                    if triple.object_curie
                    else None
                )
                session.execute(
                    insert(Triple)
                    .values(
                        subject_id=subject_id,
                        predicate=triple.predicate,
                        object_id=object_id,
                        object_literal=triple.object_literal,
                    )
                    .on_conflict_do_nothing()
                )
                count += 1

            session.commit()
        return count

    def load_ontology_properties(
        self, ontology_id: int, properties: list[ParsedProperty]
    ) -> int:
        """Load OWL object properties into the OntologyProperty table.

        Upserts on (ontology_id, curie): re-importing an ontology refreshes
        labels, domain, and range without creating duplicates.

        Returns the number of properties stored.
        """
        if not properties:
            return 0
        with Session(self.engine) as session:
            for prop in properties:
                session.execute(
                    insert(OntologyProperty)
                    .values(
                        ontology_id=ontology_id,
                        curie=prop.curie,
                        label=prop.label,
                        domain_curie=prop.domain_curie,
                        range_curie=prop.range_curie,
                    )
                    .on_conflict_do_update(
                        index_elements=["ontology_id", "curie"],
                        set_={
                            "label": prop.label,
                            "domain_curie": prop.domain_curie,
                            "range_curie": prop.range_curie,
                        },
                    )
                )
            session.commit()
        return len(properties)

    def get_project_properties(self, project_id: int) -> list[OntologyProperty]:
        """Return all OWL object properties from ontologies assigned to a project."""
        with Session(self.engine) as session:
            rows = list(
                session.scalars(
                    select(OntologyProperty)
                    .join(
                        ProjectOntology,
                        OntologyProperty.ontology_id == ProjectOntology.ontology_id,
                    )
                    .where(ProjectOntology.project_id == project_id)
                    .order_by(OntologyProperty.label)
                )
            )
            return rows

    def list_ontologies(self) -> list[Ontology]:
        """Return all ontologies stored in the database."""
        with Session(self.engine) as session:
            return list(session.scalars(select(Ontology)))

    def get_entity_types(self, query: str = "") -> list[EntityAnnotation]:
        """Return all entity classes available for annotation.

        Returns every entity in the ontology (leaf nodes included), optionally
        filtered by ``query`` against preferred name or CURIE.
        Results are sorted by preferred name.
        """
        pref_en = aliased(EntityName)
        pref_name = aliased(Name)

        stmt = (
            select(
                Entity.curie,
                Entity.type,
                pref_name.label.label("preferred_name"),
            )
            .outerjoin(pref_en, (pref_en.entity_id == Entity.entity_id) & pref_en.is_preferred)
            .outerjoin(pref_name, pref_name.id == pref_en.name_id)
            .where(Entity.curie.isnot(None), Entity.is_class == True)  # noqa: E712
        )

        if query:
            q = f"%{query}%"
            stmt = stmt.where(
                or_(
                    pref_name.label.ilike(q),
                    Entity.curie.ilike(q),
                )
            )

        with Session(self.engine) as session:
            rows = session.execute(stmt).fetchall()

        return sorted(
            [
                EntityAnnotation(
                    entity_id=row.curie,
                    preferred_name=row.preferred_name or row.curie or "",
                    kind=row.type or "",
                    synonyms=[],
                    is_class=True,
                )
                for row in rows
            ],
            key=lambda e: e.preferred_name,
        )

    def get_ontology_entities(
        self,
        ontology_id: int,
        limit: int = 50,
        offset: int = 0,
        curie_filter: str = "",
        name_filter: str = "",
        type_filter: str = "",
    ) -> tuple[list[EntityAnnotation], int]:
        """Return a page of entities for an ontology and the total count."""
        with Session(self.engine) as session:
            pref_en = aliased(EntityName)
            PrefName = aliased(Name)

            base = (
                select(
                    Entity.entity_id,
                    Entity.curie,
                    Entity.type,
                    PrefName.label.label("preferred_name"),
                )
                .outerjoin(
                    pref_en,
                    (pref_en.entity_id == Entity.entity_id) & pref_en.is_preferred,
                )
                .outerjoin(PrefName, PrefName.id == pref_en.name_id)
                .where(Entity.ontology_id == ontology_id)
            )

            if curie_filter:
                base = base.where(Entity.curie.ilike(f"%{curie_filter}%"))
            if name_filter:
                base = base.where(PrefName.label.ilike(f"%{name_filter}%"))
            if type_filter:
                base = base.where(Entity.type.ilike(f"%{type_filter}%"))

            total: int = (
                session.scalar(select(func.count()).select_from(base.subquery())) or 0
            )

            rows = session.execute(
                base.order_by(Entity.type, Entity.entity_id)
                .limit(limit)
                .offset(offset)
            ).fetchall()

            return [
                EntityAnnotation(
                    entity_id=row.curie or str(row.entity_id),
                    preferred_name=row.preferred_name or "",
                    kind=row.type,
                    synonyms=[],
                )
                for row in rows
            ], total

    def get_ontology_triples(
        self,
        ontology_id: int,
        limit: int = 50,
        offset: int = 0,
        subject_filter: str = "",
        predicate_filter: str = "",
        object_filter: str = "",
    ) -> tuple[list[dict], int]:
        """Return a page of triples whose subject belongs to the ontology.

        Each dict has: subject_curie, subject_name, predicate, object_curie,
        object_name, object_literal.  Returns (rows, total_count).
        """
        with Session(self.engine) as session:
            SubjectEnt = aliased(Entity)
            ObjectEnt = aliased(Entity)

            base = (
                select(
                    Triple.predicate,
                    Triple.object_literal,
                    SubjectEnt.curie.label("subject_curie"),
                    ObjectEnt.curie.label("object_curie"),
                )
                .join(SubjectEnt, Triple.subject_id == SubjectEnt.entity_id)
                .outerjoin(ObjectEnt, Triple.object_id == ObjectEnt.entity_id)
                .where(SubjectEnt.ontology_id == ontology_id)
            )

            if subject_filter:
                base = base.where(SubjectEnt.curie.ilike(f"%{subject_filter}%"))
            if predicate_filter:
                base = base.where(Triple.predicate.ilike(f"%{predicate_filter}%"))
            if object_filter:
                base = base.where(
                    or_(
                        ObjectEnt.curie.ilike(f"%{object_filter}%"),
                        Triple.object_literal.ilike(f"%{object_filter}%"),
                    )
                )

            total: int = (
                session.scalar(
                    select(func.count()).select_from(base.subquery())
                )
                or 0
            )

            rows = session.execute(
                base.order_by(SubjectEnt.curie, Triple.predicate)
                .limit(limit)
                .offset(offset)
            ).fetchall()

            # Resolve preferred names for all referenced CURIEs in one query
            all_curies = {r.subject_curie for r in rows if r.subject_curie} | {
                r.object_curie for r in rows if r.object_curie
            }
            curie_to_name: dict[str, str] = {}
            if all_curies:
                PrefName = aliased(Name)
                for curie, label in session.execute(
                    select(Entity.curie, PrefName.label)
                    .join(
                        EntityName,
                        EntityName.entity_id == Entity.entity_id,
                    )
                    .join(PrefName, PrefName.id == EntityName.name_id)
                    .where(
                        EntityName.is_preferred == True,  # noqa: E712
                        Entity.curie.in_(all_curies),
                    )
                ).fetchall():
                    if curie:
                        curie_to_name[curie] = label

            return [
                {
                    "subject_curie": r.subject_curie,
                    "subject_name": curie_to_name.get(r.subject_curie or "", ""),
                    "predicate": r.predicate,
                    "object_curie": r.object_curie,
                    "object_name": (
                        curie_to_name.get(r.object_curie, "")
                        if r.object_curie
                        else None
                    ),
                    "object_literal": r.object_literal,
                }
                for r in rows
            ], total

    def get_ontology_properties_by_id(
        self, ontology_id: int
    ) -> list[OntologyProperty]:
        """Return all object properties defined in a specific ontology."""
        with Session(self.engine) as session:
            return list(
                session.scalars(
                    select(OntologyProperty)
                    .where(OntologyProperty.ontology_id == ontology_id)
                    .order_by(OntologyProperty.label)
                )
            )

    def delete_ontology(self, ontology_id: int) -> None:
        """Delete an ontology and cascade-remove its entities, names, and triples."""
        with Session(self.engine) as session:
            entity_ids: list[int] = list(
                session.scalars(
                    select(Entity.entity_id).where(
                        Entity.ontology_id == ontology_id
                    )
                )
            )

            if entity_ids:
                session.execute(
                    sa_delete(Triple).where(
                        or_(
                            Triple.subject_id.in_(entity_ids),
                            Triple.object_id.in_(entity_ids),
                        )
                    )
                )

                name_ids: list[int] = list(
                    session.scalars(
                        select(EntityName.name_id).where(
                            EntityName.entity_id.in_(entity_ids)
                        )
                    )
                )

                session.execute(
                    sa_delete(EntityName).where(
                        EntityName.entity_id.in_(entity_ids)
                    )
                )

                if name_ids:
                    still_used = set(
                        session.scalars(
                            select(EntityName.name_id).where(
                                EntityName.name_id.in_(name_ids)
                            )
                        )
                    )
                    orphaned = [n for n in name_ids if n not in still_used]
                    if orphaned:
                        session.execute(
                            sa_delete(Name).where(Name.id.in_(orphaned))
                        )

                session.execute(
                    sa_delete(Entity).where(Entity.entity_id.in_(entity_ids))
                )

            session.execute(
                sa_delete(Ontology).where(Ontology.ontology_id == ontology_id)
            )
            session.commit()

        self.rebuild_fts()

    def set_curation_decision(
        self,
        project_id: int,
        relation_id: int,
        curator_id: UUID,
        verdict: Verdict,
    ) -> None:
        """Upsert a curator's accept/reject verdict on a relation triple."""
        from datetime import datetime, timezone

        with Session(self.engine) as session:
            existing = session.get(
                CurationDecision, (project_id, relation_id, curator_id)
            )
            if existing:
                existing.verdict = verdict
                existing.decided_at = datetime.now(timezone.utc)
            else:
                session.add(
                    CurationDecision(
                        project_id=project_id,
                        relation_id=relation_id,
                        curator_id=curator_id,
                        verdict=verdict,
                        decided_at=datetime.now(timezone.utc),
                    )
                )
            session.commit()

    def get_curation_decisions(
        self, project_id: int, curator_id: UUID
    ) -> dict[int, Verdict]:
        """Return all verdicts a curator has recorded for a project.

        Returns a mapping of relation_id → Verdict.
        """
        with Session(self.engine) as session:
            rows = session.scalars(
                select(CurationDecision).where(
                    CurationDecision.project_id == project_id,
                    CurationDecision.curator_id == curator_id,
                )
            ).all()
        return {row.relation_id: row.verdict for row in rows}
